name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf0e367d569417bcbd3c9c4394c6a5d3c4e541729f52d30b231a8e6522a24795"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
