name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a9172d675500ca64e9b4df8754e522ee9adf9f9cefdb024e12b1ecec4b63609"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
