name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8755e90390ef12ea30114842293e715a4fe91fd0cd98d537cf95e2d66c996ea9"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
