name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "219a273ffa19a178173c172ca70437f9c447656e04cadcc746d89fa6a3a413b9"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
